### ISSUE TITLE
Create the on-boarding form sequence

### ISSUE THREAD

**Issue by DanielMConnolly** [RychardHunt/Fyt#13]
---
name: On-boarding form sequence
---

## Feature Request

**Is your feature request related to a problem? Please describe.**
After the user registers, we need to ask the user a series of questions to get data

**Describe the solution you'd like**
We need a form component that is re-usable, you just pass in some things like label and type as props. That means it should be stateless. Maybe also pass in an onsubmit. We want this to look crisp, its the first impression for the app. Don't worry about colors or anything yet. Make the onsubmit button go through a list of things, namely ['age', 'height', 'weight', and 'date of birth'], logging them each time they are inputted.

Use Native Base

**Comment by RychardHunt** [comment]
closed by #29
