### ISSUE TITLE
[Feature] Add apache license to copyright information

### ISSUE THREAD

**Issue by astewartgit** [RychardHunt/Fyt#14]
---
name: 🚀 Add apache acknowledgement to about section somehow

---

## Feature Request

Use of the Roboto font which is part of the material-ui design language requires acknowledgements. Not an immediate priority but must be completed before launch. 

Added Roboto font to assets/fonts/roboto
See LICENSE.txt in that directory.

**Comment by RychardHunt** [comment]
Do we still need need this now that we are using NativeBase?
