### ISSUE TITLE
Create an on-boarding sequence

### ISSUE THREAD

**Issue by DanielMConnolly** [RychardHunt/Fyt#17]
---
name: 🚀 Create an on-boarding sequence
---

## Feature Request

**Is your feature request related to a problem? Please describe.**
We need to put the work of Thomas, Likith, and Matt together. Once a user registers, they are put through Thomas's on-boarding sequence, which is stored in the firebase db

**Describe the solution you'd like**
After registration, a user account is created in the db. Then, Thomas's sequence is shown, and then that stuff is also saved in the db

**Comment by RychardHunt** [comment]
closed by #29
