### ISSUE TITLE
Create a bottom navigation bar

### ISSUE THREAD

**Issue by DanielMConnolly** [RychardHunt/Fyt#3]
**Is your feature request related to a problem? Please describe.**
Our app will have a bottom navigation bar (Look at LinkedIn or Youtube app for reference). Currently, the bar will have tabs for Profile, Workout, and Diet.

**Describe the solution you'd like**
The bottom navigation bar should allow a user to click on the icon for each of the three tabs, and redirect the user to that tab. The person assigned the issue should choose three icons (can be changed later) that represent profile, workout and diet. 

**Additional context**
Do not worry about what the buttons redirect to. For now, representing the tabs by showing screens with text saying Profile, Diet, and Workout are fine.

**Comment by RychardHunt** [comment]
Closed via #11 merge
