### ISSUE TITLE
"Fix styling for login sequence"

### ISSUE THREAD

**Issue by astewartgit** [RychardHunt/Fyt#57]
---
name: 🚀 Fix styling for login sequence
about: Make the login sequence look good with the right color schemes, font sizes, layouts.

---

Corresponds to user story: "As a gym goer, I would want to be able to signup and login with the same credentials."
as seen in the linked Epic issue

## Feature Request

**Is your feature request related to a problem? Please describe.**
The login sequence is ugly

**Describe the solution you'd like**
Bring the login sequence in line with the visual identity of the project

**Describe alternatives you've considered**
Leave it ugly. Not a good idea.

**Acceptance Tests**
1. Check that the application has a consistent visual identity with well formatted components and consistent colors

**Comment by RychardHunt** [comment]
Closed via #55
